version: "3.9"

services:

  # Base de Datos - imagen desde ECR
  db:
    image: ${ECR_REGISTRY}/tienda-db:latest
    container_name: tienda-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: tienda_db
      MYSQL_USER: tienda_user
      MYSQL_PASSWORD: tienda_pass
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - red-privada
    healthcheck:
      # CORRECCIÓN: Se agrega usuario y contraseña para asegurar que el ping no falle por permisos
      test: ["CMD", "mysqladmin", "ping", "-u", "root", "-proot1234", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend Ventas
  backend-ventas:
    image: ${ECR_REGISTRY}/tienda-backend-ventas:latest
    container_name: tienda-backend-ventas
    restart: always
    environment:
      DB_ENDPOINT: db
      DB_PORT: 3306
      DB_NAME: tienda_db
      DB_USERNAME: tienda_user
      DB_PASSWORD: tienda_pass
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - red-privada
      - red-publica

  # Backend Despachos
  backend-despachos:
    image: ${ECR_REGISTRY}/tienda-backend-despachos:latest
    container_name: tienda-backend-despachos
    restart: always
    environment:
      DB_ENDPOINT: db
      DB_PORT: 3306
      DB_NAME: tienda_db
      DB_USERNAME: tienda_user
      DB_PASSWORD: tienda_pass
    ports:
      - "8081:8081"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - red-privada
      - red-publica

  # Frontend
  frontend:
    image: ${ECR_REGISTRY}/tienda-frontend:latest
    container_name: tienda-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend-ventas
      - backend-despachos
    networks:
      - red-publica

volumes:
  db-data:
    name: tienda-db-data

networks:
  red-privada:
    driver: bridge
  red-publica:
    driver: bridge